#!/bin/bash

if [ ! -e "$(command -v utserver)" ]; then echo "'utserver' not installed (correctly)..." && exit 1; fi

if [ "$1" = "start" ]; then
	sudo utserver -settingspath "$UTSERVER_BASEDIR" \
		-configfile "$UTSERVER_BASEDIR/settings.dat" \
		-logfile "$UTSERVER_BASEDIR/logs/utserver.log" \
		-pidfile "$UTSERVER_BASEDIR/utserver.pid" \
		-daemon
elif [ "$1" = "stop" ]; then
	PID=$(cat "$UTSERVER_BASEDIR/utserver.pid")
	echo "$PID"
else
	echo "usage 'utorrent-server [start|stop]'"
fi
